export const mockData = {
  universities: [
    {
      id: '1',
      name: 'Moscow Institute of Physics and Technology',
      url: 'https://mipt.ru',
    },
    {
      id: '2',
      name: 'Moscow State University',
      url: 'https://msu.ru',
    },
    {
      id: '3',
      name: 'Higher School of Economics',
      url: 'https://hse.ru',
    },
  ],
  programs: [
    {
      id: '1',
      universityId: '1',
      name: 'Applied Mathematics',
      budgetSeats: 25,
      passingScore: 250,
      contractType: 'budget' as const,
      currentRank: 22,
      originalsAbove: 18,
      examScore: 285,
      probability: 60,
    },
    {
      id: '2',
      universityId: '1',
      name: 'Computer Science',
      budgetSeats: 30,
      passingScore: 270,
      contractType: 'budget' as const,
      currentRank: 35,
      originalsAbove: 28,
      examScore: 290,
      probability: 25,
    },
    {
      id: '3',
      universityId: '2',
      name: 'Mathematics',
      budgetSeats: 40,
      passingScore: 240,
      contractType: 'budget' as const,
      currentRank: 15,
      originalsAbove: 12,
      examScore: 275,
      probability: 85,
    },
    {
      id: '4',
      universityId: '3',
      name: 'Economics',
      budgetSeats: 50,
      passingScore: 220,
      contractType: 'budget' as const,
      currentRank: 45,
      originalsAbove: 35,
      examScore: 265,
      probability: 45,
    },
  ],
};